language: shell
jobs:
  include:
  - stage: build-linux
    dist: bionic
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y dist-upgrade
    - sudo apt-get -y install awscli python3-pip python3-tk fontconfig libfreetype6
    - pip3 install --upgrade pip
    - pip3 install pyinstaller
    script:
    - pyinstaller -F m64p-updater.py
    - aws s3 cp dist/m64p-updater s3://m64p/updater/ --quiet
  - stage: build-windows
    os: windows
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    before_install:
    - choco uninstall -y mingw
    - choco install python --version=3.7.9
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade setuptools
    - python -m pip install --upgrade requests
    - python -m pip install pyinstaller
    - python -m pip install awscli
    script:
    - pyinstaller -w -F m64p-updater.py
    - aws s3 cp dist/m64p-updater.exe s3://m64p/updater/ --quiet
