jobs:
  include:
  - stage: build-linux
    dist: bionic
    language: python
    python: "3.7"
    install:
    - pip install --upgrade pip
    - pip install --upgrade setuptools
    - pip install --upgrade requests
    - pip install --upgrade pyinstaller
    - pip install --upgrade awscli
    script:
    - pyinstaller -F m64p-updater.py
    - aws s3 cp dist/m64p-updater s3://m64p/updater/ --quiet
  - stage: build-windows
    os: windows
    language: shell
    env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    before_install:
    - choco uninstall -y mingw
    - choco install -y python --version=3.7.9
    - choco install -y vcbuildtools
    - python -m pip install --upgrade pip
    - python -m pip install --upgrade setuptools
    - python -m pip install --upgrade requests
    - python -m pip install --upgrade awscli
    - wget https://github.com/pyinstaller/pyinstaller/releases/download/v4.0/PyInstaller-4.0.tar.gz
    - tar xf PyInstaller-4.0.tar.gz
    - cd pyinstaller-4.0/bootloader
    - python ./waf all
    - cd ..
    - python setup.py install
    script:
    - pyinstaller -w -F m64p-updater.py
    - aws s3 cp dist/m64p-updater.exe s3://m64p/updater/ --quiet
