language: shell
jobs:
  include:
  - stage: build-linux
    dist: bionic
    before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y install awscli
    script:
    - aws s3 cp m64p-updater.py s3://m64p/updater/ --quiet --acl public-read
  - stage: build-windows
    os: windows
    before_install:
    - choco upgrade --no-progress -y python
    - "cmd //C RefreshEnv.cmd"
    - python -m pip install pyinstaller
    script:
    - pyinstaller -F m64p-updater.py
    - aws s3 cp dist/m64p-updater.exe s3://m64p/updater/ --quiet --acl public-read
