name: Build project

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update and install packages
        run: |
          pip3 install --upgrade pip
          pip3 install --upgrade certifi
          pip3 install --upgrade setuptools
          pip3 install --upgrade requests
          pip3 install --upgrade pyinstaller
      - name: Run build script
        run: |
          python3 -m PyInstaller -F m64p-updater.py
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: m64p-updater
          path: dist/m64p-updater
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Run build script
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade certifi
          python -m pip install --upgrade setuptools
          python -m pip install --upgrade requests
          curl -O -L https://github.com/pyinstaller/pyinstaller/releases/download/v4.1/pyinstaller-4.1.tar.gz
          tar xf PyInstaller-4.1.tar.gz --directory /d
          pushd /pyinstaller-4.1/bootloader
          python ./waf all
          cd ..
          python setup.py install
          popd
          pyinstaller -w -F m64p-updater.py
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: m64p-updater.exe
          path: dist/m64p-updater.exe
